### ISSUE TITLE
Dashboard: Tags UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#669] opened 2020-03-24 17:16 UTC
**Describe the solution you'd like**
Implementation of the attached UI for tags component based on [code guidlines](https://github.com/Ignitus/Ignitus-client/wiki/CodeGuidelines-And-Conventions).

This component needs to be under [Atoms](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Atoms) which is displayed in the [ignitus-UIKit](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-UserInterfaceKit) folder at `/interface` route. 

**Additional context**
Refer [Figma](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=121%3A8) for User-Interface and other styles-related issue.

- You can view all the CSS, colors, typography, shadow effects, etc required to implement the design in the [ignitus-DesignSystem](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem) folder. Please try to follow the same pattern. 
- You can download Material rounded SVG icons as we used in Figma design and add them in [ignitus-Assets](https://github.com/Ignitus/Ignitus-client/tree/master/src/ignitus-Shared/ignitus-DesignSystem/ignitus-Assets) folder accordingly.

Mainly Tags with 4 colors white, grey, blue and orange backgrounds, and also with 2 types with and icons & text and with an cross icon on the left for all these colors. 

![dfb](https://user-images.githubusercontent.com/26546816/77456176-2a2c8100-6dfb-11ea-9eaf-c553f98fcd6f.PNG)
![fdb](https://user-images.githubusercontent.com/26546816/77456181-2ac51780-6dfb-11ea-8b34-983bc8d4aa74.PNG)
![frd](https://user-images.githubusercontent.com/26546816/77456183-2b5dae00-6dfb-11ea-924c-f7a058727310.PNG)
![gtr](https://user-images.githubusercontent.com/26546816/77456184-2b5dae00-6dfb-11ea-9208-3512683b7643.PNG)

**Comment by arpita-in** [comment] 2020-03-24 18:09
@Paarmita I would like to work on this Issue . Kindly assign it to me and guide me for the same

**Comment by Paarmita** [comment] 2020-03-24 18:14
@arpita-in Sure. I have added the folders where you need to add the tags component and you need to develop mainly 2 types of tags, one with icon and other with only text. Also, in 4 colors white, grey, blue and orange.

**Comment by Dishebh** [comment] 2020-04-09 20:03
@Paarmita if the issue is still open for take, can I work on this?

**Comment by Paarmita** [comment] 2020-04-10 06:36
@arpita-in Are you still working on it?
@Dishebh If Arpita doesn´t reply in a day, then you can take this up.

**Comment by Dishebh** [comment] 2020-04-11 20:03
> @arpita-in Sure. I have added the folders where you need to add the tags component and you need to develop mainly 2 types of tags, one with icon and other with only text. Also, in 4 colors white, grey, blue and orange.

Can you pls share the path where you added the tags component folder?

**Comment by Paarmita** [comment] 2020-04-12 16:34
@Dishebh You need to create a route under atoms and add there.

**Comment by Dishebh** [comment] 2020-04-22 20:41
@Paarmita I guess the issue can be closed now.

**Closed** 2020-04-22 20:57 UTC
Labels: RGSoC 2020, easy, gssoc20
